### ISSUE TITLE
Gitlab CI number of tests is wrong

### ISSUE THREAD

**Issue by hoppities** [spekt/junit.testlogger#42]
Version="2.1.81"

**Edit**: I updated to the latest version and have the same issue.

```yaml
Tests:
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  only:
    - merge_requests
    - branches
  script:
    - dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=../artifacts/{assembly}-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
  stage: build
  artifacts:
    when: always
    reports:
      junit:
        - $CI_PROJECT_DIR/artifacts/*-result.xml
```
This is my test step for GitLab CI, and I have tests set up with MSTest that use parameters.

```csharp
        [DataTestMethod]
        [DataRow(true)]
        [DataRow(false)]
        public async Task Some_Test_Method(bool result)
        {
            ...
        }
```

The results, however, don't show the parameters that are passed in, so they get combined into one test by Gitlab.
```xml
    <testcase classname="My.Test.Class.Name" name="name.Some_Test_Method" time="0.0147381" />
    <testcase classname="My.Test.Class.Name" name="name.Some_Test_Method" time="0.0118888" />
    <testcase classname="My.Test.Class.Name" name="name.Some_Test_Method" time="0.0003662" />
```

Expected Result: The name of the testcase will include the parameter values like the [GitLab CI Documentation](https://github.com/spekt/junit.testlogger/blob/master/docs/gitlab-recommendation.md) states.

Do I have something misconfigured?
